Layout/IndentationWidth:
  Width: 4

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength: 
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantBegin:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

