AllCops:
    NewCops: enable

Layout/CaseIndentation:
    Enabled: false

Layout/FirstHashElementIndentation:
    Enabled: false

Layout/HashAlignment:
    Enabled: false

Layout/IndentationWidth:
    Width: 4

Layout/LineLength:
    Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
    Enabled: false

Metrics/AbcSize:
    Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 24

Naming/FileName:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/GlobalVars:
    Enabled: false

Style/HashSyntax:
    EnforcedStyle: hash_rockets

Style/RaiseArgs:
    EnforcedStyle: compact
